// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wozfaoomttttvfhbystp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvemZhb29tdHR0dHZmaGJ5c3RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNjU1MzYsImV4cCI6MjA1NTc0MTUzNn0.QGnL9CZw2JJqy3sacM6p5s9cIRaSGAcm7_6MDvZSITY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);